name: Test deployment

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./site

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      - name: Install Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build